package com.example.dave.programmerpuzzle;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dave.programmerpuzzle.Puzzle;

import com.example.dave.programmerpuzzle.PuzzleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig puzzleDaoConfig;

    private final PuzzleDao puzzleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        puzzleDaoConfig = daoConfigMap.get(PuzzleDao.class).clone();
        puzzleDaoConfig.initIdentityScope(type);

        puzzleDao = new PuzzleDao(puzzleDaoConfig, this);

        registerDao(Puzzle.class, puzzleDao);
    }
    
    public void clear() {
        puzzleDaoConfig.clearIdentityScope();
    }

    public PuzzleDao getPuzzleDao() {
        return puzzleDao;
    }

}
