package com.example.dave.programmerpuzzle.Persistence.Entities;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HIGH_SCORE".
*/
public class HighScoreDao extends AbstractDao<HighScore, Long> {

    public static final String TABLENAME = "HIGH_SCORE";

    /**
     * Properties of entity HighScore.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Player = new Property(1, String.class, "player", false, "PLAYER");
        public final static Property Points = new Property(2, long.class, "points", false, "POINTS");
    }


    public HighScoreDao(DaoConfig config) {
        super(config);
    }
    
    public HighScoreDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HIGH_SCORE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PLAYER\" TEXT," + // 1: player
                "\"POINTS\" INTEGER NOT NULL );"); // 2: points
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HIGH_SCORE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HighScore entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String player = entity.getPlayer();
        if (player != null) {
            stmt.bindString(2, player);
        }
        stmt.bindLong(3, entity.getPoints());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HighScore entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String player = entity.getPlayer();
        if (player != null) {
            stmt.bindString(2, player);
        }
        stmt.bindLong(3, entity.getPoints());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HighScore readEntity(Cursor cursor, int offset) {
        HighScore entity = new HighScore( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // player
            cursor.getLong(offset + 2) // points
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HighScore entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlayer(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPoints(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HighScore entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HighScore entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HighScore entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
